server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: Gui@rese1010
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true